name: Release

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish-documentation:
    name: Publish documentation
    uses: ./.github/workflows/_publish_documentation.yaml
    permissions:
      contents: write

  release:
    needs: publish-documentation
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          version-file: pyproject.toml
          resolution-strategy: lowest

      - name: Build package
        run: uv build
        shell: bash

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
        shell: bash
